/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalis;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author MoisesGamerPro
 */
public class VentanaAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministracion
     */
    public VentanaAdministracion() {
        initComponents();
        this.setTitle("Ventana Administracion");
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
//        setSize(width/2, height/2);		
        setLocationRelativeTo(null);		
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_adminPaciente = new javax.swing.JButton();
        btn_adminCitas = new javax.swing.JButton();
        btn_adminConsultas = new javax.swing.JButton();
        btn_adminDietas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_adminPaciente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_adminPaciente.setText("Administración de pacientes");
        btn_adminPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminPacienteActionPerformed(evt);
            }
        });

        btn_adminCitas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_adminCitas.setText("Administración de citas");
        btn_adminCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminCitasActionPerformed(evt);
            }
        });

        btn_adminConsultas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_adminConsultas.setText("Administración de consultas");
        btn_adminConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminConsultasActionPerformed(evt);
            }
        });

        btn_adminDietas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_adminDietas.setText("Administración de dietas");
        btn_adminDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminDietasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel1.setText("Easy Nutrition");
        jLabel1.setMaximumSize(new java.awt.Dimension(3878, 2160));
        jLabel1.setMinimumSize(new java.awt.Dimension(3878, 2160));
        jLabel1.setPreferredSize(new java.awt.Dimension(3878, 2160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btn_adminCitas)
                        .addGap(146, 146, 146)
                        .addComponent(btn_adminDietas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_adminPaciente)
                        .addGap(107, 107, 107)
                        .addComponent(btn_adminConsultas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adminPaciente)
                    .addComponent(btn_adminConsultas))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adminDietas)
                    .addComponent(btn_adminCitas))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminPacienteActionPerformed
        AdminPaciente ap = new AdminPaciente();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adminPacienteActionPerformed

    private void btn_adminConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminConsultasActionPerformed
        AdminConsulta ac = new AdminConsulta();
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adminConsultasActionPerformed

    private void btn_adminCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminCitasActionPerformed
        AdminCita aci = new AdminCita();
        aci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adminCitasActionPerformed

    private void btn_adminDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminDietasActionPerformed
        AdminDieta ad = new AdminDieta();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adminDietasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adminCitas;
    private javax.swing.JButton btn_adminConsultas;
    private javax.swing.JButton btn_adminDietas;
    private javax.swing.JButton btn_adminPaciente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
